### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by samm82** [samm82/WorshipList#6]
# TODO
- [x] Update README
  - [x] Find better format for Contents
- [x] Add doxygen comments
- [x] Add doxygen capabilities
- [x] Better comments throughout code
- [x] Pull out key duties to getNotes()
- [x] Add README to src/ folder
